[package]
name = "arc-writer"
edition = "2024"
description = "Arc writer"
version = "0.2.1-alpha.1"
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
