[package]
name = "nanorpc-sillad"
version = "0.1.2"
edition = "2021"
description = "nanorpc transport over sillad pipes"
repository.workspace = true
license.workspace = true

[dependencies]
sillad = { version = "0.2", path = "../sillad" }
async-trait = "0.1.83"
nanorpc = "0.1.13"
serde_json = "1.0.134"
thiserror = "2.0.9"
anyhow = "1.0.95"
futures-util = { version = "0.3.31", features = ["io"] }
async-executor = "1.13.1"
