[package]
name = "nanorpc-sillad"
version = "0.1.2"
edition = "2024"
description = "nanorpc transport over sillad pipes"
repository.workspace = true
license.workspace = true

[dependencies]
sillad = { version = "0.2", path = "../sillad" }
async-trait = "0.1.86"
nanorpc = "0.1.13"
serde_json = "1.0.139"
thiserror = "2.0.11"
anyhow = "1.0.96"
futures-util = { version = "0.3.31", features = ["io"] }
async-executor = "1.13.1"
