[package]
name = "nanorpc-sillad"
version = "0.1.0"
edition = "2021"

[dependencies]
sillad = { path = "../sillad" }
async-trait = "0.1.81"
nanorpc = "0.1.12"
serde_json = "1.0.120"
thiserror = "1.0.63"
anyhow = "1.0.86"
futures-util = { version = "0.3.30", features = ["io"] }
async-executor = "1.13.0"
